# Generated by Django 6.0.3 on 2026-07-07 10:18

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('access_token', encrypted_model_fields.fields.EncryptedTextField()),
                ('refresh_token', encrypted_model_fields.fields.EncryptedTextField()),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=64)),
                ('attachment_id', models.CharField(max_length=128)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='mail_download.gmailaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('stage', models.CharField(blank=True, default='', max_length=50)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_jobs', to='mail_download.gmailaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='gmailaccount',
            index=models.Index(fields=['is_active'], name='mail_downlo_is_acti_5735ad_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadhistory',
            index=models.Index(fields=['account', 'filename', 'status'], name='mail_downlo_account_83e62f_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadhistory',
            index=models.Index(fields=['created_by', '-created_at'], name='mail_downlo_created_146e57_idx'),
        ),
        migrations.AddIndex(
            model_name='searchjob',
            index=models.Index(fields=['created_by', '-created_at'], name='mail_downlo_created_1db2c4_idx'),
        ),
    ]
