FACTORY_CODE = {
    "TBDYF": "VIYELLATEX LTD",
    "TBDEK": "EKL",
    "ABDPA": "ABDPA",
    "TBDSH": "DEWHIRST GROUP",
    "TBDSJ": "SQUARE FASHION LTD",
    "TBDSG": "SQUARE FASHION LTD",
    "TBDJK": "DBL GROUP",
    "TBDJJ": "DBL GROUP",
    "TBDAG": "ABL",
    "TBDFT": "FAKHRUDDIN TEXTILE MILLS LTD",
}