from .folder_upload_view import FolderUploadView
from .folder_batch_list_view import FolderBatchListView
from .folder_batch_detail_view import FolderBatchDetailView
from .folder_batch_logs_view import FolderBatchLogsView
from .folder_pdf_download_view import FolderPDFDownloadView
from .folder_report_list_view import FolderReportListView
from .folder_report_detail_view import FolderReportDetailView
from .folder_docx_download_view import FolderDOCXDownloadView
