# Generated by Django 6.0.3 on 2026-03-29 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('source_folder', models.CharField(max_length=512)),
                ('total_pdfs', models.PositiveIntegerField(default=0)),
                ('processed_pdfs', models.PositiveIntegerField(default=0)),
                ('failed_pdfs', models.PositiveIntegerField(default=0)),
                ('factory_code', models.CharField(blank=True, max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inspection Batch',
                'verbose_name_plural': 'Inspection Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_filename', models.CharField(max_length=512)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('style', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('po_qty', models.PositiveIntegerField(default=0)),
                ('actual_qty', models.PositiveIntegerField(default=0)),
                ('inspected_qty', models.PositiveIntegerField(default=0)),
                ('major_defect', models.CharField(blank=True, max_length=30)),
                ('minor_defect', models.CharField(blank=True, max_length=30)),
                ('factory_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('factory_name', models.CharField(blank=True, max_length=255)),
                ('final_customer', models.CharField(blank=True, max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='puma_summary.inspectionbatch')),
            ],
            options={
                'verbose_name': 'Inspection Report',
                'verbose_name_plural': 'Inspection Reports',
                'ordering': ['-inspection_date', 'style'],
            },
        ),
        migrations.CreateModel(
            name='CertificateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.CharField(blank=True, max_length=150)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_logs', to='puma_summary.inspectionreport')),
            ],
            options={
                'verbose_name': 'Certificate Log',
                'verbose_name_plural': 'Certificate Logs',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PONumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(db_index=True, max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_numbers', to='puma_summary.inspectionreport')),
            ],
            options={
                'verbose_name': 'PO Number',
                'ordering': ['number'],
                'unique_together': {('report', 'number')},
            },
        ),
    ]
