# Generated by Django 6.0.3 on 2026-03-30 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puma_summary', '0002_certificatelog_created_at_certificatelog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionbatch',
            name='excel_report_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='inspectionbatch',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inspectionbatch',
            name='source_folder',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.CreateModel(
            name='BatchFailedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=512)),
                ('reason', models.TextField(blank=True)),
                ('retried', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_failed_pdfs', to='puma_summary.inspectionbatch')),
            ],
            options={
                'verbose_name': 'Batch Failed PDF',
                'verbose_name_plural': 'Batch Failed PDFs',
                'ordering': ['filename'],
            },
        ),
    ]
