# Generated by Django 6.0.3 on 2026-03-31 09:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puma_summary', '0003_inspectionbatch_excel_report_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='report_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
