# Generated by Django 6.0.3 on 2026-04-04 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('source_folder', models.CharField(blank=True, max_length=512)),
                ('total_folders', models.PositiveIntegerField(default=0)),
                ('processed_folders', models.PositiveIntegerField(default=0)),
                ('failed_folders', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Folder Batch',
                'verbose_name_plural': 'Folder Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FolderFailedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder_name', models.CharField(max_length=512)),
                ('reason', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_failed_folders', to='image_processor.folderbatch')),
            ],
            options={
                'verbose_name': 'Folder Failed PDF',
                'verbose_name_plural': 'Folder Failed PDFs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FolderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder_name', models.CharField(max_length=512)),
                ('pdf_output_path', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='image_processor.folderbatch')),
            ],
            options={
                'verbose_name': 'Folder Report',
                'verbose_name_plural': 'Folder Reports',
                'ordering': ['-created_at', 'folder_name'],
            },
        ),
    ]
